import type {ToolDef,ToolOutput} from '../registry.js';import {z} from 'zod';
import {openProject,getSession,listSessions,updateProject,resolveProjectId} from '../../coding/session.js';
import {readProjectFile,searchProject,applyProjectPatch,projectDiff,undoProjectPatch} from '../../coding/files.js';
import {startProcess,readProcess,writeProcessInput,stopProcess} from '../../coding/processes.js';
import {askBuildQuestion,answerBuildQuestion,startProjectBuild} from '../../coding/dialogue.js';
import {activeConfig} from '../../config.js';
import {getAppPath} from '../../utils/appPath.js';
import {detectRecipe,runProjectCheck} from '../../coding/recipes.js';
import {gitProjectState,createProjectWorktree} from '../../coding/git.js';
import {startProjectPreview,showProjectPreview,inspectProjectPreview,stopProjectPreview,interactProjectPreview,assertProjectPreview} from '../../coding/preview.js';
import {inspectProjectDiagnostics,recordAcceptance,finalizeProject} from '../../coding/diagnostics.js';
import {prepareVercelDeployment,deployVercelPreview,inspectVercelDeployment,inspectVercelConnection} from '../../coding/vercel.js';
import {inspectProjectRecovery} from '../../coding/recovery.js';
import {startProjectApplication} from '../../coding/application.js';
import {CODING_TOOL_NAMES} from '../../coding/tool-selection.js';
const id=z.string().min(1).max(128).describe('Project UUID returned by open_project, or an exact unique owned project name.');const revision=z.number().int().min(0).describe('Current project revision; inspect after a conflict.');
const wrap=(fn:(a:any)=>Promise<unknown>|unknown)=>async(a:any):Promise<ToolOutput>=>{try{if(typeof a.projectId==='string')a={...a,projectId:resolveProjectId(a.projectId)};const data=await fn(a);return {status:'success',verification:'unverified',text:JSON.stringify(data),data};}catch(error:any){return {status:'failed',verification:'unverified',text:error.message,error:{category:/conflict/i.test(error.message)?'conflict':'coding',message:error.message,retryable:false}};}};
export const CODING_TOOLS:ToolDef[]=[
 {name:'inspect_coding_tools',description:'Get exact validated coding action schemas by name. For small-context brains, discover one or two actions here and call invoke_coding_tool with that action and its arguments.',schema:{names:z.array(z.string()).min(1).max(3)},readOnly:true,handler:wrap(a=>a.names.map((name:string)=>{const tool=CODING_TOOLS.find(t=>t.name===name&&CODING_TOOL_NAMES.includes(name));if(!tool)throw new Error('Unknown coding action.');return {name,description:tool.description,schema:z.toJSONSchema(z.object(tool.schema),{io:'input'})};}))},
 {name:'invoke_coding_tool',description:'Call one coding action using its exact schema from inspect_coding_tools. Inner action still passes shared validation, risk confirmation, task ownership and resource leases. Use action open_project to begin.',schema:{action:z.enum(CODING_TOOL_NAMES as [string,...string[]]),arguments:z.record(z.string(),z.unknown())},readOnly:false,handler:async a=>{try{const tool=CODING_TOOLS.find(t=>t.name===a.action&&CODING_TOOL_NAMES.includes(t.name));if(!tool)return {status:'failed',text:'Unknown coding action.'};const {runGated}=await import('../../safety/gate.js');return runGated(tool,a.arguments,{workingDir:typeof a.arguments.projectId==='string'?getSession(resolveProjectId(a.arguments.projectId)).root:getAppPath()});}catch(error:any){return {status:'failed',verification:'unverified',text:error.message};}}},
 {name:'inspect_vercel_connection',description:'Check privately saved Vercel credentials with an authenticated read and list up to five accessible project IDs/names. Does not upload or publish; supply teamId for a team-scoped token.',schema:{teamId:z.string().optional()},readOnly:true,handler:wrap(a=>inspectVercelConnection(a.teamId))},
 {name:'inspect_project_recovery',description:'Inspect durable project/question state, source fingerprint, existing owned processes and deployment records before resuming. Never automatically duplicates installs, servers or uncertain publication.',schema:{projectId:id},readOnly:true,handler:wrap(a=>inspectProjectRecovery(a.projectId))},
 {name:'start_project_application',description:'Run the detected/configured application start command as an owned persistent process. Native GUI windows belong to that application. Inspect logs/readiness; a process launch alone does not prove its UI works or distribution is signed.',schema:{projectId:id,revision},readOnly:false,handler:wrap(a=>startProjectApplication(a.projectId,a.revision))},
 {name:'prepare_vercel_deployment',description:'Prepare a reviewable small web deployment manifest without uploading anything. Excludes hidden/dependency files and refuses apparent credentials; maximum 100 files / 1 MiB. Requires explicit Vercel project/team identifiers.',schema:{projectId:id,vercelProject:z.string(),teamId:z.string().optional()},readOnly:true,handler:wrap(async a=>{const plan=await prepareVercelDeployment(a.projectId,a.vercelProject,a.teamId);return {...plan,files:plan.files.map(f=>({file:f.file,bytes:Buffer.from(f.data,'base64').length}))};})},
 {name:'deploy_vercel_preview',description:'Publish a prepared small project to Vercel preview using the private settings token. Never deploy production. Persists source fingerprint and deployment ID; uncertain submissions refuse automatic retries. Requires user authorization through the shared gate.',schema:{projectId:id,revision,vercelProject:z.string(),teamId:z.string().optional()},readOnly:false,handler:wrap(a=>deployVercelPreview(a.projectId,a.revision,a.vercelProject,a.teamId))},
 {name:'inspect_vercel_deployment',description:'Poll an owned deployment state and source fingerprint. READY means provider readiness, not tested user flows or accessibility through preview protection.',schema:{projectId:id,deploymentId:z.string()},readOnly:true,handler:wrap(a=>inspectVercelDeployment(a.projectId,a.deploymentId))},
 {name:'inspect_project_diagnostics',description:'Read check outcomes against the current content revision, logs, stale evidence and repeated failure signatures. Stop repair after three identical failures and report the blocker.',schema:{projectId:id},readOnly:true,handler:wrap(a=>inspectProjectDiagnostics(a.projectId))},
 {name:'record_project_acceptance',description:'Attach concrete observed test/browser evidence to one saved acceptance criterion at the current revision. This is an agent observation requiring independent dataset review, not certified gold.',schema:{projectId:id,revision,criterion:z.string(),evidence:z.string()},readOnly:false,handler:wrap(a=>recordAcceptance(a.projectId,a.revision,a.criterion,a.evidence))},
 {name:'finalize_project',description:'Mark complete only when recorded current checks exited successfully and every saved acceptance criterion has current evidence. Direct update_project completion is refused.',schema:{projectId:id,revision},readOnly:false,handler:wrap(a=>finalizeProject(a.projectId,a.revision))},
 {name:'interact_project_preview',description:'Exercise one local preview control with an exact single-match DOM selector and click/fill action. Then inspect the resulting DOM/console/network to verify the user flow.',schema:{projectId:id,selector:z.string(),action:z.enum(['click','fill']),value:z.string().default('')},readOnly:false,handler:wrap(a=>interactProjectPreview(a.projectId,a.selector,a.action,a.value))},
 {name:'assert_project_preview',description:'Assert one exact single-match preview DOM text or form value against an expected value. Fails on mismatch; optionally records the actual observation for a saved acceptance criterion. Exercise controls first and cover every relevant flow.',schema:{projectId:id,revision,selector:z.string(),expected:z.string().max(12000),criterion:z.string().optional()},readOnly:false,handler:wrap(a=>assertProjectPreview(a.projectId,a.revision,a.selector,a.expected,a.criterion))},
 {name:'start_project_preview',description:'Start a managed local website server using detected static/dev/start recipe and wait for loopback HTTP readiness. Returns URL/process ID; HTTP readiness does not prove user flows.',schema:{projectId:id,revision},readOnly:false,handler:wrap(a=>startProjectPreview(a.projectId,a.revision))},
 {name:'show_project_preview',description:'Show the managed project website in an isolated browser window without Echo preload or Node access.',schema:{projectId:id},readOnly:false,handler:wrap(a=>showProjectPreview(a.projectId))},
 {name:'inspect_project_preview',description:'Read observed DOM controls, bounded page text, console and network status from the isolated preview window. Compare with acceptance criteria rather than inferring success from file creation.',schema:{projectId:id},readOnly:true,handler:wrap(a=>inspectProjectPreview(a.projectId))},
 {name:'stop_project_preview',description:'Close the isolated project window and stop its owned managed server.',schema:{projectId:id},readOnly:false,handler:wrap(a=>stopProjectPreview(a.projectId))},
 {name:'start_project_build',description:'Build or continue a saved project through the supervised worker/inspector workflow automatically. Retained for existing coding sessions; run_supervised_task also accepts explicit plans and criteria. No user mode switch is needed. Assigned supervised workers implement directly with project tools; another active task is refused.',schema:{projectId:id,request:z.string()},readOnly:false,handler:wrap(a=>startProjectBuild(a.projectId,a.request,activeConfig(getAppPath())))},
 {name:'ask_build_question',description:'Ask one architecture/feature/theme question that blocks building. Persists it and pauses the coding worker; the next user answer resumes the saved project. Routine implementation choices should use sensible defaults.',schema:{projectId:id,revision,question:z.string(),options:z.array(z.string()).max(4).default([])},readOnly:false,handler:wrap(a=>askBuildQuestion(a.projectId,a.revision,a.question,a.options))},
 {name:'answer_build_question',description:'Record a user answer to the exact pending build question. Stale question IDs are refused. The foreground voice coordinator normally handles answers automatically.',schema:{projectId:id,questionId:z.string().uuid(),answer:z.string()},readOnly:false,handler:wrap(a=>answerBuildQuestion(a.projectId,a.questionId,a.answer))},
 {name:'inspect_project_recipe',description:'Detect existing project language, package manager, configured checks and missing executable probes. This does not prove the app compiles. Unknown stacks require inspection.',schema:{projectId:id},readOnly:true,handler:wrap(a=>detectRecipe(a.projectId))},
 {name:'run_project_checks',description:'Start a configured project build/test/lint/typecheck/check or install job and return its managed process ID. Inspect read_process for actual exit; unavailable checks are failures, not invented successes.',schema:{projectId:id,revision,check:z.enum(['build','test','lint','typecheck','check','install'])},readOnly:false,handler:wrap(a=>runProjectCheck(a.projectId,a.revision,a.check))},
 {name:'open_project',description:'Open or create a dedicated coding project outside Echo’s installation. Omit path for a new project in ~/EchoProjects/name. Returns project ID/revision. Use first when asked to build or edit software.',schema:{path:z.string().optional(),name:z.string().optional(),create:z.boolean().optional(),spec:z.string().optional(),target:z.string().default('web')},readOnly:false,handler:wrap(openProject)},
 {name:'inspect_project',description:'Read a saved coding project or list your projects. Get current revision, requirements, progress and process IDs before resuming or editing.',schema:{projectId:id.optional()},readOnly:true,handler:wrap(a=>a.projectId?getSession(a.projectId):listSessions())},
 {name:'update_project',description:'Save coding requirements, acceptance criteria, language and phase at the current revision. This records a plan, not proof that a build succeeded.',schema:{projectId:id,revision,phase:z.enum(['clarifying','planning','implementing','waiting-for-input','verifying','previewing','deploying','completed','blocked','failed','cancelled']).optional(),spec:z.string().optional(),target:z.string().optional(),language:z.string().optional(),framework:z.string().optional(),decisions:z.array(z.string()).optional(),acceptance:z.array(z.string()).optional()},readOnly:false,handler:wrap(a=>{const {projectId,revision,...changes}=a;return updateProject(projectId,revision,changes);})},
 {name:'search_project',description:'List or search project files/text, ignoring dependencies, Git internals and env files. Results state truncation; do not interpret a bounded search as complete.',schema:{projectId:id,query:z.string().default(''),limit:z.number().int().min(1).max(100).default(50)},readOnly:true,handler:wrap(a=>searchProject(a.projectId,a.query,a.limit))},
 {name:'read_project_file',description:'Read a UTF-8 project file with content hash, revision and character pagination. Use its hash for guarded patches and nextOffset to read the rest.',schema:{projectId:id,path:z.string(),offset:z.number().int().min(0).default(0),limit:z.number().int().min(1).max(12000).default(6000)},readOnly:true,handler:wrap(a=>readProjectFile(a.projectId,a.path,a.offset,a.limit))},
 {name:'apply_project_patch',description:'Atomically create/edit/remove one project file using expected content hash and project revision. Use missing for a new file. Preserves existing content on conflict; stores a reversible patch.',schema:{projectId:id,revision,path:z.string(),expectedHash:z.string(),content:z.string().optional(),edits:z.array(z.object({before:z.string().min(1),after:z.string()})).optional(),remove:z.boolean().optional()},readOnly:false,handler:wrap(a=>applyProjectPatch(a.projectId,a.revision,a))},
 {name:'project_diff',description:'Inspect a saved project patch with bounded before/after text and explicit truncation.',schema:{projectId:id,patchId:z.string().uuid()},readOnly:true,handler:wrap(a=>projectDiff(a.projectId,a.patchId))},
 {name:'undo_project_patch',description:'Undo exactly one Echo project patch only if the file still matches that patch’s result. Refuses to overwrite newer user edits.',schema:{projectId:id,revision,patchId:z.string().uuid()},readOnly:false,handler:wrap(a=>undoProjectPatch(a.projectId,a.revision,a.patchId))},
 {name:'start_process',description:'Start a managed executable with argument array inside a coding project. Returns processId immediately; poll read_process for logs/exit status. Set timeoutMs:0 only for an intentional persistent dev server. Subprocesses do not inherit Echo API keys. This is not OS sandboxing.',schema:{projectId:id,revision,program:z.string(),args:z.array(z.string()).default([]),cwd:z.string().default('.'),timeoutMs:z.number().int().min(0).max(3600000).default(120000),pty:z.boolean().default(false)},readOnly:false,handler:wrap(a=>startProcess(a.projectId,a.revision,a))},
 {name:'read_process',description:'Poll managed process output with character cursor and actual status/exitCode. outputLost indicates ring-buffer truncation. Polling never owns the stop/write lease.',schema:{projectId:id,processId:z.string().uuid(),offset:z.number().int().min(0).default(0),limit:z.number().int().min(1).max(12000).default(6000)},readOnly:true,handler:wrap(a=>readProcess(a.projectId,a.processId,a.offset,a.limit))},
 {name:'write_process_input',description:'Send text to stdin of a currently owned live project process. Use pty:true on start_process for macOS programs requiring a TTY.',schema:{projectId:id,processId:z.string().uuid(),text:z.string().max(16000)},readOnly:false,handler:wrap(a=>writeProcessInput(a.projectId,a.processId,a.text))},
 {name:'stop_process',description:'Stop only the verified project-owned process group. Never signal an unverifiable stale saved PID.',schema:{projectId:id,processId:z.string().uuid()},readOnly:false,handler:wrap(a=>stopProcess(a.projectId,a.processId))},
 {name:'project_git_status',description:'Inspect Git HEAD, dirty status and diff summary for a project repository root; does not stage or discard user changes.',schema:{projectId:id},readOnly:true,handler:wrap(a=>gitProjectState(a.projectId))},
 {name:'create_project_worktree',description:'Create a coding project in a new Git worktree from HEAD using safe argument-array execution. Original dirty files stay untouched and are not copied.',schema:{projectId:id,branch:z.string().optional()},readOnly:false,handler:wrap(a=>createProjectWorktree(a.projectId,a.branch))},
];
