import assert from 'node:assert/strict';import {app,BrowserWindow,ipcMain,protocol} from 'electron';import {resolve} from 'node:path';import {mkdirSync,writeFileSync} from 'node:fs';import {installPreviewBridge} from './preview_fixtures.mjs';import {report,assertions} from './markdown-fixture.mjs';
const root=resolve(import.meta.dirname,'..');mkdirSync('/tmp/echo-panel-markdown-test',{recursive:true});app.setPath('userData','/tmp/echo-panel-markdown-test');app.on('window-all-closed',()=>{});installPreviewBridge(ipcMain);
const now=Date.now(),result={status:'completed',summary:report,artifacts:[],verificationRefs:[],blockers:[]},mission={id:'bot-markdown-fixture',goal:'Research AI',status:'completed',scope:{echoBot:true},createdAt:now,updatedAt:now,tasks:{research:{id:'research',profile:'research',goal:'Research AI',status:'completed',result,budget:{maxIterations:40,maxRecoveryAttempts:2,timeoutMs:600000},dependsOn:[]}},result};
ipcMain.handle('control:bots',()=>({bots:[{id:'research',name:'Research',role:'Find facts',revision:'a'.repeat(24),mode:'native tools'}],jobs:[{id:mission.id,botId:'research',botName:'Research',goal:'Research AI',status:'completed',updatedAt:now,result,steps:[],live:false}]}));
app.whenReady().then(async()=>{protocol.handle('https',()=>new Response(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64'),{headers:{'Content-Type':'image/png'}}));let win,failed=false;const settle=()=>new Promise(r=>setTimeout(r,100));
 try {win=new BrowserWindow({width:1180,height:760,show:false,webPreferences:{preload:resolve(root,'dist/preload.cjs'),contextIsolation:true,sandbox:true}});const js=c=>win.webContents.executeJavaScript(c),page={evaluate:(fn,arg)=>js(`(${fn.toString()})(${JSON.stringify(arg)??'undefined'})`)};
 await win.loadFile(resolve(root,'renderer/control-panel.html'));win.showInactive();await js(`setView('bots')`);await settle();await assertions(page,'#bots-jobs .echo-markdown');
 await js(`render({...snapshot,missions:[${JSON.stringify(mission)}]});window.echoAgentsUI.inspect(${JSON.stringify(mission.id)})`);await settle();await assertions(page,'#board-answer-text .echo-markdown');
 for(const width of [1180,900,680]){win.setSize(width,600);await settle();assert.ok(await js(`document.documentElement.scrollWidth<=innerWidth`));await js(`setView('bots')`);await settle();assert.ok(await js(`document.documentElement.scrollWidth<=innerWidth`));await js(`setView('tasks')`);}
 win.setSize(1180,760);await js(`setView('bots')`);await settle();writeFileSync('/tmp/echo-mac-markdown.png',(await win.webContents.capturePage()).toPNG());
 await js(`byId('bots-jobs').querySelector('.echo-markdown img').dispatchEvent(new Event('error'))`);assert.equal(await js(`byId('bots-jobs').querySelectorAll('.echo-image-unavailable').length`),1);win.destroy();
 win=new BrowserWindow({width:1040,height:900,show:false,webPreferences:{preload:resolve(root,'dist/report-preload.cjs'),contextIsolation:true,sandbox:true}});
 await win.loadFile(resolve(root,'renderer/task-report.html'));win.showInactive();const task={id:'report-fixture',status:'completed',title:'AI research',duration:'1 minute',summary:'Completed research',steps:[],reviews:[],checks:[],outputs:[{label:'Research report',value:report}],blockers:[],cleanup:'All workers stopped.'};
 await win.webContents.executeJavaScript(`window.renderTaskReport({report:${JSON.stringify(task)}})`);await settle();const taskPage={evaluate:(fn,arg)=>win.webContents.executeJavaScript(`(${fn.toString()})(${JSON.stringify(arg)??'undefined'})`)};await assertions(taskPage,'#report-outputs .rows .echo-markdown');
 console.log('PASS Mac Electron Bots, Agents canonical report and task outputs: semantic Markdown, credited pictures, literal HTML, unsafe URL rejection, image failure, responsive layouts and speech cleanup.');
 }catch(e){failed=true;console.error(e);}finally{win?.destroy();app.exit(failed?1:0);}
});
