import assert from 'node:assert/strict';import {app,BrowserWindow,ipcMain} from 'electron';import {resolve} from 'node:path';import {mkdirSync,writeFileSync} from 'node:fs';import {installPreviewBridge} from './preview_fixtures.mjs';
const root=resolve(import.meta.dirname,'..');mkdirSync('/tmp/echo-panel-bots-test',{recursive:true});app.setPath('userData','/tmp/echo-panel-bots-test');installPreviewBridge(ipcMain);
let fail=false,reads=0,failNextAction=false;const actions=[],now=Date.now();const state={bots:[{id:'research',name:'Research',role:'Find facts',description:'Find verified facts',revision:'a'.repeat(24),mode:'native tools'},{id:'plan',name:'Plan',role:'Prepare a plan',revision:'c'.repeat(24),mode:'native tools'},{id:'review',name:'Review',role:'Check evidence',revision:'d'.repeat(24),mode:'native tools'},{id:'echo:team',name:'Team of specialists',role:'Reports then combined answer',revision:'b'.repeat(24),team:true,defaultAgentIds:['research','plan','review'],mode:'read tools'}],jobs:[{id:'bot-fixture',botId:'research',botName:'Research',goal:'<img src=x onerror=window.injected=true>',status:'completed',updatedAt:now,result:{summary:'Verified report',blockers:[],artifacts:[{kind:'text',label:'Same report',value:'Verified report'}]},steps:[{name:'Research',status:'completed',result:{summary:'Verified report'}}],live:false}]};
ipcMain.handle('control:bots',()=>{reads++;if(fail)throw Error('Private backend details');return structuredClone(state);});ipcMain.removeHandler('control:action');ipcMain.handle('control:action',(_e,a)=>{actions.push(a);if(failNextAction){failNextAction=false;throw Error('Fixture transport interruption');}return {ok:true,message:'Accepted'};});
app.whenReady().then(async()=>{const win=new BrowserWindow({width:1180,height:760,show:false,webPreferences:{preload:resolve(root,'dist/preload.cjs'),contextIsolation:true,sandbox:true}});const js=c=>win.webContents.executeJavaScript(c),settle=()=>new Promise(r=>setTimeout(r,100));let failed=false;const errors=[];win.webContents.on('console-message',(_e,level,message)=>{if(level>=3&&!message.includes('Content Security Policy'))errors.push(message);});
 try{win.showInactive();await win.loadFile(resolve(root,'renderer/control-panel.html'));await settle();assert.equal(reads,0);await js(`setView('tasks');document.querySelector('[data-view="bots"]').click()`);await settle();assert.equal(await js('activeView'),'bots');assert.match(await js(`byId('bots-jobs').textContent`),/Verified report/);assert.equal(await js(`byId('bots-jobs').textContent.split('Verified report').length-1`),1);assert.equal(await js(`!!byId('bots-jobs').querySelector('img')||!!window.injected`),false);
 // One task appears in both views; inspector links only open a draft, never dispatch work.
 await js(`render({...snapshot,missions:[{id:'bot-fixture',goal:'Canonical task',status:'completed',scope:{echoBot:true},createdAt:Date.now(),updatedAt:Date.now(),tasks:{research:{id:'research',profile:'research',goal:'Canonical task',status:'completed',result:{status:'completed',summary:'Verified report',artifacts:[],verificationRefs:[],blockers:[]},budget:{maxIterations:40,maxRecoveryAttempts:2,timeoutMs:600000},dependsOn:[]}},result:{status:'completed',summary:'Verified report',artifacts:[],verificationRefs:[],blockers:[]}}]});byId('bots-jobs').querySelector('button:last-child').click()`);await settle();assert.equal(await js('activeView'),'tasks');assert.equal(await js('currentBoardMissionId'),'bot-fixture');assert.match(await js(`byId('board-answer-text').textContent`),/Verified report/);assert.equal(await js(`!!byId('board-task')||!!document.querySelector('[data-agent-compose]')`),false);
 const beforeDraft=actions.length;await js(`document.querySelector('[data-task-agent="research"]').click()`);await settle();assert.equal(await js('activeView'),'bots');assert.equal(await js(`byId('bots-member').value`),'research');assert.equal(actions.length,beforeDraft);
 await js(`byId('bots-goal').value='Keep this draft';window.echoBotsUI.sync()`);await settle();assert.equal(await js(`byId('bots-goal').value`),'Keep this draft');await js(`byId('bots-run').requestSubmit()`);await settle();assert.equal(actions.at(-1).type,'run-bot');assert.equal(actions.at(-1).botRevision,'a'.repeat(24));assert.match(actions.at(-1).requestId,/^[a-f0-9-]{36}$/);
 await js(`byId('bots-jobs').querySelector('button').click();byId('bots-goal').value='Explain the sources';byId('bots-run').requestSubmit()`);await settle();assert.equal(actions.at(-1).parentId,'bot-fixture');assert.notEqual(actions.at(-1).requestId,actions.at(-2).requestId);
 // A failed transport retains the exact ID on retry; rapid submission cannot launch twice.
 failNextAction=true;await js(`byId('bots-goal').value='Retry the same task';byId('bots-run').requestSubmit();byId('bots-run').requestSubmit()`);await settle();const retryId=actions.at(-1).requestId,retryCount=actions.length;await js(`byId('bots-run').requestSubmit()`);await settle();assert.equal(actions.length,retryCount+1);assert.equal(actions.at(-1).requestId,retryId);
 await js(`setView('tasks');byId('board-team').click()`);await settle();assert.equal(await js(`byId('bots-member').value`),'echo:team');assert.equal(await js(`byId('bots-team').hidden`),false);
 await js(`byId('bots-goal').value='Team draft';byId('bots-team-members').querySelector('input[value="review"]').click();window.echoBotsUI.sync()`);await settle();assert.equal(await js(`byId('bots-team-members').querySelector('input[value="review"]').checked`),false);assert.equal(await js(`byId('bots-goal').value`),'Team draft');await js(`byId('bots-run').requestSubmit()`);await settle();assert.equal(actions.at(-1).name,'echo:team');assert.deepEqual(actions.at(-1).agentIds,['plan','research']);assert.equal(actions.at(-1).botRevision,'b'.repeat(24));
 await js(`byId('bots-member').value='research';byId('bots-member').dispatchEvent(new Event('change'))`);await settle();
 state.jobs[0].live=true;state.jobs[0].status='running';await js(`window.echoBotsUI.sync()`);await settle();await js(`byId('bots-jobs').querySelector('button').click()`);await settle();assert.equal(actions.at(-1).type,'stop-bot');assert.equal(actions.at(-1).missionId,'bot-fixture');await js(`byId('bots-manage').click()`);await settle();assert.equal(await js(`byId('fleet-dialog').open`),true);await js(`byId('fleet-close').click();setView('bots')`);await settle();
 for(const width of [1180,900,680]){win.setSize(width,600);await settle();const fits=await js(`(()=>{const p=byId('bots-view'),s=p.querySelector('.companion-scroll');s.scrollTop=s.scrollHeight;return document.documentElement.scrollWidth<=innerWidth&&p.getBoundingClientRect().right<=innerWidth+1&&s.lastElementChild.getBoundingClientRect().bottom<=s.getBoundingClientRect().bottom+1;})()`);assert.ok(fits,`Bots fits at ${width}`);}
 for(const width of [1180,900,680]){win.setSize(width,600);await js(`setView('tasks')`);await settle();assert.ok(await js(`document.documentElement.scrollWidth<=innerWidth&&byId('tasks-view').getBoundingClientRect().right<=innerWidth+1`),`Agents fits at ${width}`);}
 win.setSize(1180,760);await js(`setView('bots')`);await settle();writeFileSync('/tmp/echo-mac-bots.png',(await win.webContents.capturePage()).toPNG());fail=true;await js(`window.echoBotsUI.sync()`);await settle();assert.match(await js(`byId('bots-status').textContent`),/Couldn’t read/);assert.ok(!await js(`document.body.textContent.includes('Private backend details')`));assert.deepEqual(errors,[]);console.log('PASS shared Bots/Agents task identity, inspector-only task links, team selection, preserved draft, exact retry IDs, no rapid duplicate submit, Mac Bots navigation, exact bridge actions, safe results, preserved drafts, follow-up, Stop, fleet editor, responsive scrolling and failure handling.');
 }catch(e){failed=true;console.error(e);}finally{win.destroy();app.exit(failed?1:0);}
});
