import assert from 'node:assert/strict';
import {BackgroundBrowser} from './browser/background.js';
let closed=0, loaded='';
const page={load:async(url:string)=>{loaded=url;}, read:async()=>({url:loaded,title:'Dynamic page',text:'Rendered content',links:[]}), close:()=>{closed++;}};
const browser=new BackgroundBrowser(()=>page);
assert.equal((await browser.read('https://example.org')).text,'Rendered content');
assert.equal(closed,1);
await assert.rejects(browser.read('file:///etc/passwd'),/HTTP/);
await assert.rejects(browser.read('https://user:password@example.org'),/credentials/);
assert.equal(closed,1);
const stuck=new BackgroundBrowser(()=>({...page,load:()=>new Promise<void>(()=>{})}));
await assert.rejects(stuck.read('https://example.org',{timeoutMs:10}),/deadline/);
assert.equal(closed,2,'deadline closes the hidden renderer');
const controller=new AbortController();
const pending=stuck.read('https://example.org',{signal:controller.signal}); controller.abort();
await assert.rejects(pending,/cancelled/); assert.equal(closed,3);
const active=stuck.read('https://example.org');
await assert.rejects(stuck.read('https://example.org'),/busy/);
stuck.close(); await assert.rejects(active,/closed/); assert.equal(closed,4);
await assert.rejects(stuck.read('https://example.org'),/closed/);
console.log('Background browser protocol, extraction, deadlines, cancellation, cap and cleanup passed');
