import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
const root=await mkdtemp(join(tmpdir(),'echo-build-latency-'));process.env.ECHO_DATA_ROOT=join(root,'data');process.env.ECHO_MEMORY_ROOT=join(root,'memory');process.env.ECHO_LOG_DIR=join(root,'runs');process.env.ECHO_MCP='0';process.env.ECHO_LOG_QUIET='1';
const {Brain}=await import('./brain/types.js');const {DEFAULTS_FOR_TESTS}=await import('./config.js');const {openProject,getSession}=await import('./coding/session.js');const {startProjectBuild,handleBuildInput,askBuildQuestion,stopCodingWorkers}=await import('./coding/dialogue.js');const {isBuildStatusRequest}=await import('./coding/progress.js');const {codingContinuationEligible}=await import('./coding/continuation.js');const {isPlaybackTranscript}=await import('./voice/interjection.js');const {streamStep,StreamStalledError}=await import('./brain/stream-deadline.js');const {TOOL_MAP}=await import('./tools/registry.js');const {GeminiBrain}=await import('./brain/gemini.js');const {RecordingBrain}=await import('./agent-replay/runtime.js');const {ExternalToolCatalog}=await import('./brain/external-tool-catalog.js');const {modelHealth}=await import('./brain/model-health.js');
class Probe extends Brain{messages:string[]=[];interrupts=0;send(t:string){this.messages.push(t);}interrupt(){this.interrupts++;}async stop(){this.interrupt();}}
try{
 const p=await openProject({path:join(root,'site'),create:true,name:'StudyForge'});await writeFile(join(p.root,'package.json'),'{}');const worker=new Probe();await startProjectBuild(p.id,'Build StudyForge',DEFAULTS_FOR_TESTS,()=>worker);
 for(const query of ['did you finish?','Did you finish','have you finished yet?','are you done?','are you stuck?','what are you doing?']){assert(isBuildStatusRequest(query),query);const start=performance.now();const answer=await handleBuildInput(query,DEFAULTS_FOR_TESTS);assert.match(answer!,/StudyForge/);assert(performance.now()-start<200);}
 assert.equal(worker.messages.length,1);assert.equal(worker.interrupts,0);const waiting=await askBuildQuestion(p.id,getSession(p.id).revision,'Which theme?');await handleBuildInput('did you finish',DEFAULTS_FOR_TESTS);assert.equal(getSession(p.id).question?.answer,undefined);assert.equal(getSession(p.id).question?.id,waiting.question?.id);await stopCodingWorkers();console.log('PASS instant saved-state status, no cloud call, no worker interruption and no accidental question answer');
 const verification=TOOL_MAP.get('verify_task')!;const checks=[{kind:'file_exists',path:join(p.root,'package.json')}];assert.equal((await verification.handler({checks})).verification,'contradicted');const milestone=await verification.handler({checks,scope:'artifact',summary:'Created package manifest'});assert.equal(milestone.verification,'verified');assert.equal((milestone.data as any).projectCompletionVerified,false);assert.match(milestone.text!,/completion remains unverified/);console.log('PASS intermediate artifact verification succeeds while full app completion still fails');
 const echo="I'm continuing the assembly of StudyForge by initializing the project structure for your minimalist dashboard and setting up the necessary dependencies.";
 assert(isPlaybackTranscript(echo,echo));assert(isPlaybackTranscript("I'm continuing the assembly of StudyForge by initialising the project structure for your minimalist dashboard and setting up the necessary dependencies.",echo));for(const text of ['did you finish?','No, do it as I said.','Build StudyForge with a minimalist dashboard and a real persistent backend.','Please continue the assembly of StudyForge by initializing the project structure for your minimalist dashboard.'])assert(!isPlaybackTranscript(text,echo),text);console.log('PASS recorded self-speech variations rejected; real commands, corrections and status questions preserved');
 assert(codingContinuationEligible(false,true,"I'll start by initializing the project."));assert(codingContinuationEligible(false,true,'Now installing dependencies and assembling the dashboard.'));assert(!codingContinuationEligible(false,true,'What visual theme do you want?'));assert(!codingContinuationEligible(false,true,'I can build applications. Let me know what you want.'));assert(!codingContinuationEligible(false,false,"I'll begin preparing the report."));for(const said of ["I can certainly build a small 2D game for you now; let's get started.","Got it, I'm setting up a new project for your 2D game now.","I'm starting a 2D game project for you now, using a simple HTML5 canvas approach.","Okay, I'm building it now."])assert(codingContinuationEligible(false,true,said),said);assert(!codingContinuationEligible(false,true,'Should we get started on something simple now, or would you prefer to save this for tomorrow?'));console.log('PASS spoken build promises with no tool call are nudged into action');
 {const {ProviderMemoryContext}=await import('./memory/provider-context.js');const {conversations}=await import('./memory/conversation.js');const ctx=new ProviderMemoryContext('gemini');conversations.append('a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a1',{role:'user',provider:'gemini',actorId:'echo',text:'Build a small game, a 2D game.'});ctx.begin('Go ahead.',{conversationId:'a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a1'});assert(ctx.isCodingTurn(),'go ahead after build talk');conversations.append('a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a2',{role:'user',provider:'gemini',actorId:'echo',text:'Tell me a story.'});ctx.begin('Go ahead.',{conversationId:'a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a2'});assert(!ctx.isCodingTurn(),'go ahead after chat');ctx.close();console.log('PASS "Go ahead" after build talk keeps the coding tools and guidance');}
 const {PiperWorker}=await import('./voice/tts-stream.js');let ownedVoiceStops=0;(PiperWorker as any).workers.set('owned-fixture',{stop:()=>ownedVoiceStops++});PiperWorker.stopAll();PiperWorker.stopAll();assert.equal(ownedVoiceStops,1);console.log('PASS shared Piper workers released once on shutdown');
 const {shutdownStep}=await import('./shutdown.js');const shutdownMessages:string[]=[];assert.equal(await shutdownStep('hung fixture',()=>new Promise(()=>{}),20,t=>shutdownMessages.push(t)),false);assert.equal(await shutdownStep('next resource',()=>Promise.resolve(),20),true);assert.equal(await shutdownStep('throwing fixture',()=>{throw Error('failed');},20,t=>shutdownMessages.push(t)),false);assert.equal(shutdownMessages.length,2);console.log('PASS shutdown continues after stalled or throwing services');
 const request=new AbortController();await assert.rejects(streamStep(()=>new Promise(()=>{}),request,20),StreamStalledError);assert(request.signal.aborted);const parent=new AbortController(),child=new AbortController();const aborted=streamStep(()=>new Promise(()=>{}),child,1000,parent.signal);parent.abort(new Error('User stopped'));await assert.rejects(aborted,/User stopped/);assert(child.signal.aborted);assert.equal(await streamStep(()=>Promise.resolve('ready'),new AbortController(),20),'ready');console.log('PASS stalled SDK request is cancelled, ignored-abort requests still reject, and user abort never waits for timeout');
 const catalog=new ExternalToolCatalog([{name:'mcp__fixture__GMAIL_CREATE_DRAFT',description:'Create a mail draft for a project',schema:{}}] as any);await catalog.begin('Build a website project');assert.equal(catalog.selected.size,0);await catalog.discover('gmail draft');assert(catalog.selected.has('mcp__fixture__GMAIL_CREATE_DRAFT'));console.log('PASS unrelated mail schemas omitted from coding startup; explicit discovery still loads them');
 const cfg=structuredClone(DEFAULTS_FOR_TESTS);cfg.agi.toolPruning.enabled=false;cfg.gemini.model='silent-fixture';process.env.ECHO_GEMINI_STREAM_SILENCE_MS='20';const brain=new GeminiBrain(cfg,'offline') as any;const requested:string[]=[];let successes=0;let silentSignal:AbortSignal|undefined;
 brain.ai={models:{generateContentStream:async(r:any)=>{requested.push(r.model);if(r.model==='silent-fixture'){silentSignal=r.config.abortSignal;return new Promise(()=>{});}successes++;const parts=successes===1?[{text:"I'll start by inspecting the project."}]:successes===2?[{functionCall:{name:'inspect_project',args:{projectId:p.id}}}]:[{text:'Project inspection is complete.'}];return (async function*(){yield {candidates:[{content:{role:'model',parts},finishReason:'STOP'}]};})();}}};
 const recorded=new RecordingBrain(brain,'test',{}, {autoResume:false});const updates:string[]=[];recorded.on('progress',t=>updates.push(t));const done=new Promise<void>(resolve=>recorded.once('turnEnd',resolve));recorded.send('Build the website project.');await Promise.race([done,new Promise<never>((_,reject)=>setTimeout(()=>reject(Error('Offline loop timeout')),4000))]);await recorded.stop();assert.equal(requested.filter(m=>m==='silent-fixture').length,1);assert(silentSignal?.aborted);assert(!modelHealth.usable('silent-fixture'));assert(successes>=3);assert(updates.some(t=>t.includes('stopped responding')));console.log('PASS actual Gemini SDK path falls back on silence, forwards progress and starts concrete work after a first-step promise');
 {const {codingActionRequest}=await import('./coding/continuation.js');for(const q of ['Build a small game, a 2D game.','Go ahead.','I go build it.','No, do it as I said.','Fix the login bug'])assert(codingActionRequest(q),q);for(const q of ['Can you build an application?','Can you build an application','How is the build going','No, don\'t build it yet.','Build it tomorrow.'])assert(!codingActionRequest(q),q);
  const forcedCfg=structuredClone(DEFAULTS_FOR_TESTS);forcedCfg.agi.toolPruning.enabled=false;forcedCfg.gemini.model='forced-fixture';
  const run=async(text:string)=>{const b=new GeminiBrain(forcedCfg,'offline') as any;const configs:any[]=[];let n=0;
   b.ai={models:{generateContentStream:async(r:any)=>{configs.push(r.config);n++;const parts=n===1&&r.config.toolConfig?[{functionCall:{name:'inspect_project',args:{projectId:p.id}}}]:[{text:'Done.'}];return (async function*(){yield {candidates:[{content:{role:'model',parts},finishReason:'STOP'}]}})()}}};
   const rec=new RecordingBrain(b,'test',{}, {autoResume:false});const end=new Promise<void>(resolve=>rec.once('turnEnd',resolve));rec.send(text);await Promise.race([end,new Promise<never>((_,reject)=>setTimeout(()=>reject(Error('forced fixture timeout')),4000))]);await rec.stop();return configs;};
  const build=await run('Build a small game, a 2D game.');const fc=build[0].toolConfig?.functionCallingConfig;assert.equal(fc?.mode,'ANY');assert(fc.allowedFunctionNames.includes('open_project'));assert(fc.allowedFunctionNames.includes('run_supervised_task'));assert(!fc.allowedFunctionNames.includes('recall'));assert(!fc.allowedFunctionNames.includes('web_search'));assert(build.length>=2&&!build[1].toolConfig,'only the first step is forced');
  const asked=await run('Can you build an application?');assert(!asked[0].toolConfig,'a question is answered, not forced');
  console.log('PASS Gemini must call a coding tool before replying to a build instruction; questions still get an answer');}
}finally{delete process.env.ECHO_GEMINI_STREAM_SILENCE_MS;await stopCodingWorkers();await rm(root,{recursive:true,force:true});}
