import {createHash} from 'node:crypto';
import {app,BrowserWindow} from 'electron';import {mkdtemp,copyFile,rm,writeFile,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import assert from 'node:assert/strict';
app.on('window-all-closed',()=>{});app.setPath('userData',join(tmpdir(),'echo-calculator-ui-test'));setTimeout(()=>app.exit(1),30000).unref();
void app.whenReady().then(async()=>{app.getAppPath=()=>process.cwd();const root=await mkdtemp(join(tmpdir(),'echo-calculator-ui-'));process.env.ECHO_DATA_ROOT=join(root,'data');process.env.ECHO_MEMORY_ROOT=join(root,'memory');
const {openProject,getSession,updateProject}=await import('./coding/session.js');const {showProjectPreview,inspectProjectPreview,interactProjectPreview,assertProjectPreview,stopProjectPreview,closeProjectPreviews,startProjectPreview}=await import('./coding/preview.js');const {stopAllCodingProcesses}=await import('./coding/processes.js');
try{const p=await openProject({path:join(root,'calculator'),create:true,name:'calculator'});await copyFile(join(process.cwd(),'tests/coding/calculator.html'),join(p.root,'index.html'));await updateProject(p.id,0,{acceptance:['Arithmetic flows work']});await showProjectPreview(p.id);
 const preview=await startProjectPreview(p.id,getSession(p.id).revision);closeProjectPreviews();const recovered=await startProjectPreview(p.id,getSession(p.id).revision);assert.equal(recovered.processId,preview.processId);assert.equal(recovered.reused,true);await showProjectPreview(p.id);
 const click=async(label:string)=>{const controls=(await inspectProjectPreview(p.id)).dom.controls;const i=controls.findIndex((c:any)=>c.tag==='BUTTON'&&c.text===label);assert(i>=0,label);const buttons=controls.filter((c:any)=>c.tag==='BUTTON');const index=buttons.findIndex((c:any)=>c.text===label)+1;await interactProjectPreview(p.id,`button:nth-of-type(${index})`,'click');};
 const check=async(keys:string[],expected:string)=>{await click('C');for(const key of keys)await click(key);await assertProjectPreview(p.id,getSession(p.id).revision,'#display',expected,'Arithmetic flows work');};
 for(const [keys,result] of [[['2','+','3','='],'5'],[['9','-','4','='],'5'],[['6','*','7','='],'42'],[['8','/','2','='],'4'],[['1','/','0','='],'Error'],[['0','/','0','='],'Error'],[['0','.','1','+','0','.','2','='],'0.3'],[['2','+','3','*','4','='],'14'],[['-','2','+','5','='],'3'],[['2','+','='],'Error'],[['2','+','*','3','='],'6'],[['1','.','.','5','+','2','='],'3.5']] as [string[],string][]){await check(keys,result);}
 await click('4');await assertProjectPreview(p.id,getSession(p.id).revision,'#display','4');await check(['1','/','0','='],'Error');await click('7');await assertProjectPreview(p.id,getSession(p.id).revision,'#display','7');await assert.rejects(assertProjectPreview(p.id,getSession(p.id).revision,'#display','invented'),/assertion failed/);
 const win=BrowserWindow.getAllWindows()[0];await win.webContents.executeJavaScript(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));for(const key of ['8','/','2','Enter'])document.dispatchEvent(new KeyboardEvent('keydown',{key}));`);await assertProjectPreview(p.id,getSession(p.id).revision,'#display','4');win.setContentSize(320,600);const fits=await win.webContents.executeJavaScript('document.querySelector(".calc").getBoundingClientRect().right<=innerWidth');assert(fits);
 const observed=await inspectProjectPreview(p.id);assert(!observed.console.some((line:string)=>/^3:/.test(line)));await stopProjectPreview(p.id);await writeFile('/private/tmp/echo-calculator-ui-result.json',JSON.stringify({passed:true,sourceHash:createHash('sha256').update(await readFile(join(p.root,'index.html'))).digest('hex'),flows:12,errorRecovery:true,keyboard:true,viewportWidth:320,previewRecovery:true}));console.log('PASS 12 real calculator button flows, error recovery, fresh entry, keyboard, 320px fit, failed assertion refusal and saved preview server recovery');
}catch(error){console.error(error);process.exitCode=1;}finally{await stopAllCodingProcesses();await rm(root,{recursive:true,force:true});app.exit(process.exitCode ? 1 : 0);}});
