import {app} from 'electron';import {mkdtemp,writeFile,copyFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import assert from 'node:assert/strict';
app.on('window-all-closed',()=>{});app.setPath('userData',join(tmpdir(),'echo-coding-ui-test'));setTimeout(()=>{console.error('coding UI timeout');app.exit(1);},20000).unref();
void app.whenReady().then(async()=>{app.getAppPath=()=>process.cwd();const root=await mkdtemp(join(tmpdir(),'echo-coding-ui-'));process.env.ECHO_DATA_ROOT=join(root,'data');process.env.ECHO_MEMORY_ROOT=join(root,'memory');
const {openProject}=await import('./coding/session.js');const {startProjectPreview,showProjectPreview,inspectProjectPreview,interactProjectPreview,stopProjectPreview}=await import('./coding/preview.js');const {stopAllCodingProcesses}=await import('./coding/processes.js');
try{const project=await openProject({path:join(root,'site'),create:true});await writeFile(join(project.root,'index.html'),`<title>Fixture</title><input id="name"><button id="submit">Save</button><p id="result"></p><script>console.log('isolation:'+typeof require+':'+typeof window.jarvis);console.error('seeded-error');document.querySelector('#submit').onclick=()=>document.querySelector('#result').textContent='Saved '+document.querySelector('#name').value;</script>`);
 await startProjectPreview(project.id,0);await showProjectPreview(project.id);await interactProjectPreview(project.id,'#name','fill','Ada');await interactProjectPreview(project.id,'#submit','click');const result=await inspectProjectPreview(project.id);assert.match(result.dom.text,/Saved Ada/);assert(result.console.some(line=>line.includes('isolation:undefined:undefined')));assert(result.console.some(line=>line.includes('seeded-error')));assert(result.network.some(line=>line.startsWith('200')));await stopProjectPreview(project.id);
 const backend=await openProject({path:join(root,'backend'),create:true});await copyFile(join(process.cwd(),'tests/coding/python_service.py'),join(backend.root,'server.py'));await writeFile(join(backend.root,'echo.project.json'),JSON.stringify({language:'Python',commands:{start:{program:'python3',args:['server.py']}}}));await writeFile(join(backend.root,'index.html'),`<input id="item"><button id="save">Save</button><p id="items"></p><script>document.querySelector('#save').onclick=async()=>{await fetch('/api/items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:document.querySelector('#item').value})});const data=await (await fetch('/api/items')).json();document.querySelector('#items').textContent=data.map(row=>row.text).join(',');};</script>`);const backendPreview=await startProjectPreview(backend.id,0);await showProjectPreview(backend.id);await interactProjectPreview(backend.id,'#item','fill','Browser persisted item');await interactProjectPreview(backend.id,'#save','click');let backendResult;for(let n=0;n<100;n++){backendResult=await inspectProjectPreview(backend.id);if(backendResult.dom.text.includes('Browser persisted item'))break;await new Promise(r=>setTimeout(r,30));}assert.match(backendResult!.dom.text,/Browser persisted item/);assert.equal((await (await fetch(new URL('/api/items',backendPreview.url))).json())[0].text,'Browser persisted item');await stopProjectPreview(backend.id);
 await writeFile('/private/tmp/echo-coding-ui-result.json',JSON.stringify({passed:true,result}));console.log('PASS isolated browser DOM flow, console errors, network evidence, no Node/Echo bridge and Python UI/API/SQLite flow');
}catch(error){await writeFile('/private/tmp/echo-coding-ui-result.json',JSON.stringify({passed:false,error:String(error)}));console.error(error);process.exitCode=1;}finally{await stopAllCodingProcesses();await rm(root,{recursive:true,force:true});app.quit();}

});
