import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import assert from 'node:assert/strict';
const root=await mkdtemp(join(tmpdir(),'echo-vercel-'));process.env.ECHO_DATA_ROOT=join(root,'data');process.env.ECHO_MEMORY_ROOT=join(root,'memory');
const {openProject,getSession}=await import('./coding/session.js');const {prepareVercelDeployment,deployVercelPreview,inspectVercelDeployment}=await import('./coding/vercel.js');const {classify}=await import('./safety/risk.js');
try{const project=await openProject({path:join(root,'site'),create:true});await writeFile(join(project.root,'index.html'),'<h1>Fixture</h1>');await writeFile(join(project.root,'.env'),'secret=not-uploaded');const plan=await prepareVercelDeployment(project.id,'fixture');assert.deepEqual(plan.files.map(f=>f.file),['index.html']);assert.equal(classify('deploy_vercel_preview',{}, {workingDir:root}).tier,'high');delete process.env.VERCEL_TOKEN;
 await assert.rejects(deployVercelPreview(project.id,0,'fixture',undefined,async()=>{throw Error('should not call');}),/token is missing/);
 // A failed/uncertain submission never gets retried automatically. A different source is a new reviewable attempt.
 process.env.VERCEL_TOKEN='fixture-private-token';await assert.rejects(deployVercelPreview(project.id,getSession(project.id).revision,'fixture',undefined,async()=>{throw Error('connection lost');}),/connection lost/);await assert.rejects(deployVercelPreview(project.id,getSession(project.id).revision,'fixture'),/uncertain outcome/);await writeFile(join(project.root,'index.html'),'<h1>New fixture</h1>');let posts=0;
 const mock:typeof fetch=async(url,init)=>{assert.equal((init?.headers as any).Authorization,'Bearer fixture-private-token');if(init?.method==='POST'){posts++;const body=JSON.parse(String(init.body));assert.equal(body.target,undefined);assert.equal(body.files.length,1);return new Response(JSON.stringify({id:'dpl_fixture',readyState:'BUILDING',url:'fixture.vercel.app'}));}return new Response(JSON.stringify({id:'dpl_fixture',readyState:'READY',url:'fixture.vercel.app'}));};
 const deployment=await deployVercelPreview(project.id,getSession(project.id).revision,'fixture',undefined,mock);assert.equal(deployment.state,'BUILDING');const ready=await inspectVercelDeployment(project.id,'dpl_fixture',mock);assert.equal(ready.state,'READY');assert.equal(ready.sourceStale,false);await deployVercelPreview(project.id,getSession(project.id).revision,'fixture',undefined,mock);assert.equal(posts,1);assert(!JSON.stringify(getSession(project.id)).includes('fixture-private-token'));console.log('PASS Vercel manifest, private auth, preview-only request, persisted ownership, READY status and no duplicate submissions (mock API)');
}finally{delete process.env.VERCEL_TOKEN;await rm(root,{recursive:true,force:true});}
