import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import assert from 'node:assert/strict';
const root=await mkdtemp(join(tmpdir(),'echo-coding-improvements-'));process.env.ECHO_DATA_ROOT=join(root,'data');process.env.ECHO_MEMORY_ROOT=join(root,'memory');process.env.ECHO_MCP='0';process.env.ECHO_LOG_QUIET='1';process.env.ECHO_LOG_DIR=join(root,'runs');
const {openProject,resolveProjectId,getSession}=await import('./coding/session.js');const {TOOL_MAP}=await import('./tools/registry.js');const {ProviderMemoryContext}=await import('./memory/provider-context.js');const {conversations,conversationId,contextTokens}=await import('./memory/conversation.js');const {inspectVercelConnection}=await import('./coding/vercel.js');
try{
 const project=await openProject({path:join(root,'one'),create:true,name:'calculator',spec:'Keep the calculator keyboard accessible.'});await writeFile(join(project.root,'index.html'),'<h1>Calculator</h1>');
 assert.equal(resolveProjectId('calculator'),project.id);assert.equal((await TOOL_MAP.get('inspect_project')!.handler({projectId:'calculator'})).status,'success');
 const {runInAgentContext}=await import('./agent-replay/context.js');const outsider={identity:{id:'outsider'}} as any;assert.throws(()=>runInAgentContext(outsider,()=>resolveProjectId('calculator')),/No owned/);assert.throws(()=>runInAgentContext(outsider,()=>resolveProjectId(project.id)),/no grant/);
 const verification=await TOOL_MAP.get('verify_task')!.handler({checks:[{kind:'file_exists',path:join(project.root,'index.html')}],summary:'Calculator is built and works'});assert.equal(verification.verification,'contradicted');assert.match(verification.text ?? "",/File existence alone/);
 const cid=conversationId('echo');for(let n=0;n<30;n++)conversations.append(cid,{role:'user',actorId:'echo',provider:'gemini',text:`Build calculator step ${n} ${'old details '.repeat(500)}`});
 const memory=new ProviderMemoryContext('gemini');memory.begin('Show the calculator project',{conversationId:cid});const packet=memory.packet();assert(contextTokens(packet)<=4000);assert(packet.includes(project.id));assert(packet.includes('keyboard accessible'));ProviderMemoryContext.cloudRecall=false;assert(!memory.packet().includes('keyboard accessible'));ProviderMemoryContext.cloudRecall=true;memory.close();
 await openProject({path:join(root,'two'),create:true,name:'calculator'});assert.throws(()=>resolveProjectId('calculator'),/Ambiguous/);assert.throws(()=>resolveProjectId('missing'),/No owned/);
 process.env.VERCEL_TOKEN='fixture-private-token';let calls=0;const connection=await inspectVercelConnection(undefined,(async(url:any,options:any)=>{calls++;assert.equal(options.method,'GET');assert.match(url,/v10\/projects\?limit=5$/);assert.equal(options.headers.Authorization,'Bearer fixture-private-token');assert.equal(options.body,undefined);return new Response(JSON.stringify({projects:[{id:'prj_fixture',name:'fixture',env:[{value:'must-not-leak'}]}]}),{status:200});}) as typeof fetch);assert.equal(calls,1);assert.equal(connection.connected,true);assert(!JSON.stringify(connection).includes('must-not-leak'));
 console.log(`PASS unique aliases, ambiguous rejection, file-only app verification rejection, bounded coding memory (${contextTokens(packet)} tokens), retained project IDs and private read-only Vercel connection`);
 const {DEFAULTS_FOR_TESTS}=await import('./config.js');const {GeminiBrain}=await import('./brain/gemini.js');const {RecordingBrain}=await import('./agent-replay/runtime.js');const cfg=structuredClone(DEFAULTS_FOR_TESTS);cfg.gemini.model='quota-fixture';cfg.agi.toolPruning.enabled=false;const brain=new GeminiBrain(cfg,'offline') as any;const requested:string[]=[];let successes=0;
 brain.generateStreaming=async(r:any)=>{requested.push(r.model);if(r.model==='quota-fixture')throw new Error('429 quota exceeded');successes++;return {candidates:[{content:{role:'model',parts:successes===1?[{functionCall:{name:'inspect_project',args:{projectId:project.id}}}]:[{text:'The project state is available.'}]},finishReason:'STOP'}]};};
 const recording=new RecordingBrain(brain,'gemini',{}, {autoResume:false});const done=new Promise<void>(resolve=>recording.once('turnEnd',resolve));recording.send('Inspect the calculator project');await Promise.race([done,new Promise<never>((_,reject)=>{setTimeout(()=>reject(new Error('Fallback test timed out')),5000).unref();})]);await recording.stop();assert.equal(requested.filter(m=>m==='quota-fixture').length,1);assert(successes>=2);assert.equal(requested[1],requested[2]);console.log('PASS actual Gemini multi-step loop keeps the working fallback and never re-asks the exhausted model');
}finally{await rm(root,{recursive:true,force:true});}
