import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {companionProjection,companionMemory,saveCompanionMemory,forgetCompanionMemory,phoneUpdateIntent,type CompanionWork} from './control-companion.js';
import {MemoryService,memoryService} from './memory/service.js';
import {ConfirmationBroker} from './safety/confirm.js';
import {PhoneUpdates} from './frontier/phone-updates.js';
const root=mkdtempSync(join(tmpdir(),'echo-companion-'));let n=0;const check=(f:()=>void)=>{f();n++;};
const now=Date.now(),work=(extra:Partial<CompanionWork>={}):CompanionWork=>({id:'task-a',kind:'task',title:'Prepare report',status:'running',updatedAt:now,revision:1,summary:'',privateMode:false,live:true,...extra});
try{
 check(()=>{const p=companionProjection({work:[work(),work({id:'project-a',kind:'project',taskId:'task-a',status:'waiting-for-input',question:{id:'q1',text:'Choose the date',options:['Friday']}})],approval:null,now});assert.equal(p.work.length,1);assert.equal(p.needs.length,1);assert.match(p.next,/Resolve/);});
 check(()=>{const p=companionProjection({work:[work({status:'done',updatedAt:now-8*86400_000}),work({id:'live',title:'<script>x</script>',updatedAt:now-20*86400_000})],approval:{id:'expired',question:'No',expiresAt:now-1},now});assert.equal(p.work.length,1);assert.equal(p.approval,null);});
 check(()=>{for(const t of ['Send me updates to my phone','Echo, send me updates on my phone.','I’m leaving','Please keep me updated on my phone'])assert.equal(phoneUpdateIntent(t),'start');for(const t of ['Stop sending updates to my phone','Don’t send me updates to my phone'])assert.equal(phoneUpdateIntent(t),'stop');for(const t of ['How do I send me updates to my phone?','don’t keep me updated on my phone','He said send me updates to my phone','I’m leaving a note','Send this file to my phone'])assert.equal(phoneUpdateIntent(t),null);});
 check(()=>{const p=companionProjection({work:[work({live:false})],approval:null,now});assert.equal(p.now.length,0);assert.equal(p.needs.length,1);});
 check(()=>{const p=companionProjection({work:[work({id:'root'}),work({id:'mission',kind:'mission',taskId:'root'}),work({id:'project',kind:'project',linkedTaskIds:['root']})],approval:null,now});assert.deepEqual(p.work.map(w=>w.id),['project']);});
 const store=new MemoryService(join(root,'memory'));
 const note=saveCompanionMemory({text:'I prefer morning meetings',kind:'preference'},{projectId:'alpha'},store);
 check(()=>{assert.equal(note.source.trust,'user_asserted');assert.equal(companionMemory({},'',store).items.length,0);assert.equal(companionMemory({projectId:'alpha'},'morning',store).items.length,1);});
 check(()=>{assert.throws(()=>saveCompanionMemory({id:note.id,revision:999,text:'Afternoon'}, {projectId:'alpha'},store),/changed/);assert.throws(()=>saveCompanionMemory({id:note.id,revision:note.revision,text:'Afternoon'},{projectId:'beta'},store),/scope/);});
 const changed=saveCompanionMemory({id:note.id,revision:note.revision,text:'I prefer afternoon meetings'},{projectId:'alpha'},store);
 check(()=>{assert.equal(changed.revision,2);assert.equal(changed.embedding,undefined);assert.equal(companionMemory({projectId:'alpha'},'morning',store).items.length,0);assert.equal(companionMemory({projectId:'alpha'},'afternoon',store).items[0].id,note.id);});
 const persisted=saveCompanionMemory({text:'Test removable note'},{});
 check(()=>{assert.throws(()=>forgetCompanionMemory({id:persisted.id,revision:0},{}),/changed/);const r=forgetCompanionMemory({id:persisted.id,revision:1},{});assert.equal(r.count,1);assert.equal(memoryService.get(persisted.id),undefined);});
 const broker=new ConfirmationBroker();const promise=broker.request('Allow this exact action?',10000);const approval=broker.current()!;
 check(()=>{assert.equal(broker.settle('different',true),false);assert.equal(broker.current()?.id,approval.id);assert.equal(broker.settle(approval.id,true),true);assert.equal(broker.settle(approval.id,false),false);});assert.equal(await promise,true);n++;
 let time=now;const file=join(root,'outbox.json'),updates=new PhoneUpdates(()=>file,()=>time);
 check(()=>assert.throws(()=>updates.begin({generation:0,devices:[],pushDevices:0},[]),/connect/));
 updates.begin({generation:1,devices:['a'.repeat(32)],pushDevices:0},[work(),work({id:'private',privateMode:true})]);
 check(()=>{assert.equal(updates.snapshot().queued,1);assert.match(updates.snapshot().message,/Enable notifications/);});
 updates.observe([work(),work({id:'private',privateMode:true,status:'done'})]);check(()=>assert.equal(updates.snapshot().queued,1));
 updates.observe([work({status:'completed',summary:'Report verified'})]);updates.observe([work({status:'completed',summary:'Another log'})]);check(()=>assert.equal(updates.snapshot().queued,2));
 const sent:string[]=[];await updates.flush(async e=>{sent.push(e.id);return null;});check(()=>assert.equal(updates.snapshot().queued,2));
 const recovered=new PhoneUpdates(()=>file,()=>time);await recovered.flush(async e=>{sent.push(e.id);return {ok:true,pending:true,recipients:1};});check(()=>assert.equal(sent[0],sent[1]));
 await recovered.flush(async e=>{sent.push(e.id);assert.ok(!e.body.includes('private'));return {ok:true,recipients:1,pushes:0};});check(()=>{assert.equal(recovered.snapshot().queued,0);assert.match(recovered.snapshot().message,/Delivered to Phone Missions/);});
 recovered.observe([work({status:'blocked'})],{id:'approval-a',question:'Allow publishing?'});const queued=recovered.snapshot().queued;recovered.observe([work({status:'blocked'})],{id:'approval-a',question:'Allow publishing?'});check(()=>assert.equal(recovered.snapshot().queued,queued));
 let release!:(r:any)=>void;const flight=recovered.flush(()=>new Promise(r=>release=r));await Promise.resolve();recovered.stop();release({ok:true,recipients:1,pushes:1});await flight;check(()=>{assert.equal(recovered.snapshot().active,false);assert.equal(recovered.snapshot().queued,0);assert.match(recovered.snapshot().message,/off/);});
 recovered.begin({generation:1,devices:['a'.repeat(32)],pushDevices:1},[]);time+=24*3600_000+1;check(()=>{assert.equal(recovered.snapshot().active,false);assert.equal(recovered.snapshot().queued,0);});
 recovered.begin({generation:1,devices:['a'.repeat(32)],pushDevices:0},[]);recovered.reconcile({generation:2,devices:[],pushDevices:0});check(()=>assert.equal(recovered.snapshot().active,false));
 const fast=new PhoneUpdates(()=>join(root,'fast.json'),()=>time);fast.begin({generation:2,devices:['b'.repeat(32)],pushDevices:0},[]);fast.observe([work({id:'fast',status:'done',updatedAt:time}),work({id:'historical',status:'done',updatedAt:time-1000})]);check(()=>assert.equal(fast.snapshot().queued,2));fast.observe([work({id:'saved',status:'running',live:false,updatedAt:time})]);await fast.flush(async e=>{if(e.body.includes('saved'))assert.equal(e.kind,'needs-you');return {ok:true,recipients:1};});check(()=>assert.equal(fast.snapshot().queued,0));
 console.log(`${n}/${n} control companion checks passed`);
}finally{rmSync(root,{recursive:true,force:true});}
