import {createHash} from 'node:crypto';import {getSession,mutateSession} from './session.js';import {detectRecipe} from './recipes.js';
import {projectFingerprint} from './snapshot.js';
import {readProcess} from './processes.js';
export async function inspectProjectDiagnostics(id:string){const session=getSession(id);const fingerprint=await projectFingerprint(id);const checks=[];const signatures=new Map<string,number>();
 for(const artifact of session.artifacts.filter(a=>a.kind==='check').slice(-30)){const check=JSON.parse(artifact.value);const process=await readProcess(id,check.processId);const signature=createHash('sha256').update(`${check.name}:${process.exitCode}:${process.output.replace(/\d+/g,'#').slice(-3000)}`).digest('hex');if(process.status==='failed')signatures.set(signature,(signatures.get(signature)??0)+1);checks.push({...check,status:process.status,exitCode:process.exitCode,output:process.output,stale:check.contentRevision!==(session.contentRevision??0)||check.fingerprint!==fingerprint.hash,signature});}
 return {projectId:id,revision:session.revision,contentRevision:session.contentRevision??0,checks,stopRepair:[...signatures.values()].some(n=>n>=3),guidance:'Stop after three identical failing signatures. Reproduce one issue, guarded patch, then rerun the affected check. Passing checks do not verify untested user flows.'};
}
export async function recordAcceptance(id:string,revision:number,criterion:string,evidence:string,expectedFingerprint?:string){const session=getSession(id);if(!session.acceptance.includes(criterion))throw new Error('Criterion must be in saved project acceptance criteria.');if(evidence.trim().length<10)throw new Error('Provide concrete observed evidence, not a success label.');const fingerprint=await projectFingerprint(id);if(expectedFingerprint&&fingerprint.hash!==expectedFingerprint)throw new Error('Source changed since the browser observation.');return (await mutateSession(id,revision,s=>{s.artifacts.push({kind:'acceptance-evidence',value:JSON.stringify({criterion,evidence,fingerprint:fingerprint.hash,contentRevision:s.contentRevision??0})});})).session;}
/** Shared read-only readiness guard; generic file checks must not bypass it. */
export async function inspectProjectCompletion(id:string){const session=getSession(id);const fingerprint=await projectFingerprint(id);const diagnostics=await inspectProjectDiagnostics(id);const latest=new Map(diagnostics.checks.filter(c=>!c.stale).map(c=>[c.name,c]));const required=Object.keys((await detectRecipe(id)).commands).filter(name=>!['install','dev','start'].includes(name));const blockers:string[]=[];
 if(!required.length||required.some(name=>!latest.has(name)||latest.get(name)!.status!=='exited'||latest.get(name)!.exitCode!==0))blockers.push('Current checks are missing, running or failing.');
 if(!session.acceptance.length)blockers.push('Define acceptance criteria before completion.');
 const evidence=session.artifacts.filter(a=>a.kind==='acceptance-evidence').map(a=>JSON.parse(a.value));
 if(session.acceptance.some(criterion=>!evidence.some(e=>e.criterion===criterion&&e.fingerprint===fingerprint.hash&&e.contentRevision===(session.contentRevision??0))))blockers.push('Current acceptance evidence is missing.');
 return {projectId:id,ready:blockers.length===0,blockers};
}
export async function finalizeProject(id:string,revision:number){const completion=await inspectProjectCompletion(id);if(!completion.ready)throw new Error(completion.blockers.join(' '));return (await mutateSession(id,revision,s=>{s.phase='completed';})).session;}
