import {readFile,readdir,mkdir,statfs} from 'node:fs/promises';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {join} from 'node:path';
import {getSession,mutateSession} from './session.js';import {projectPath} from './workspace.js';import {startProcess,readProcess} from './processes.js';
import {getAppPath} from '../utils/appPath.js';
import {projectFingerprint} from './snapshot.js';
const exec=promisify(execFile);
export interface ProjectRecipe {kind:'static-web'|'node-web'|'python'|'configured'|'rust'|'go'|'swift'|'java'|'unknown';language:string;commands:Record<string,{program:string;args:string[];nodeMode?:boolean}>;missing:string[];notes:string[];}
export async function detectRecipe(id:string):Promise<ProjectRecipe>{
 const session=getSession(id);await projectPath(session.root);const files=await readdir(session.root);
 if(files.includes('echo.project.json')) {const config=JSON.parse(await readFile(await projectPath(session.root,'echo.project.json'),'utf8'));const commands:ProjectRecipe['commands']={};for(const [name,value] of Object.entries(config.commands??{}) as Array<[string,any]>){if(!['dev','start','build','test','lint','typecheck','check','install'].includes(name)||typeof value.program!=='string'||!Array.isArray(value.args)||!value.args.every((v:unknown)=>typeof v==='string'))throw new Error('Invalid echo.project.json command contract.');commands[name]={program:value.program,args:value.args};}return {kind:'configured',language:String(config.language??session.language??'configured'),commands,missing:[],notes:['Explicit project commands are used as configured. Missing dependencies are reported by actual process exits. All executions require shared gate review.']};}
 if(files.includes('package.json')) {
  const pkg=JSON.parse(await readFile(join(session.root,'package.json'),'utf8'));const commands:ProjectRecipe['commands']={};
  const manager=files.includes('pnpm-lock.yaml')?'pnpm':files.includes('yarn.lock')?'yarn':'npm';
  for(const [name,value] of Object.entries(pkg.scripts??{}))if(['dev','start','build','test','lint','typecheck','check'].includes(name)&&typeof value==='string')commands[name]={program:manager,args:['run',name]};
  commands.install={program:manager,args:manager==='npm'?(files.includes('package-lock.json')?['ci']:['install']):['install']};
  const missing:string[]=[];for(const command of ['node',manager])try{await exec(command,['--version'],{cwd:session.root,timeout:10000});}catch{missing.push(command);}
  return {kind:'node-web',language:files.some(name=>name==='tsconfig.json')?'TypeScript':'JavaScript',commands,missing,notes:['Existing package scripts are retained. A package script may execute arbitrary code; all execution passes the project gate.']};
 }
 if(files.includes('pyproject.toml')||files.includes('requirements.txt')||files.some(name=>name.endsWith('.py'))){let available=true;try{await exec('python3',['--version'],{timeout:10000});}catch{available=false;}
  return {kind:'python',language:'Python',commands:{check:{program:'python3',args:['-m','compileall','-q','.']}},missing:available?[]:['python3'],notes:['Choose an entrypoint/API server explicitly; do not guess framework or install system-wide dependencies.']};}
 for(const adapter of [
 {marker:'Cargo.toml',kind:'rust',language:'Rust',program:'cargo',commands:{check:['check'],build:['build'],test:['test'],start:['run']}},
 {marker:'go.mod',kind:'go',language:'Go',program:'go',commands:{check:['vet','./...'],build:['build','-o','.echo-build/Application','.'],test:['test','./...'],start:['run','.']}},
 {marker:'Package.swift',kind:'swift',language:'Swift',program:'swift',commands:{check:['build'],build:['build'],test:['test'],start:['run']}},
 {marker:'main.swift',kind:'swift',language:'Swift',program:'swiftc',commands:{check:['-typecheck','main.swift'],build:['main.swift','-o','.echo-build/Application']}}
 ] as const){if(!files.includes(adapter.marker))continue;let available=true;try{await exec(adapter.program,['--version'],{timeout:10000});}catch{available=false;}const commands:ProjectRecipe['commands']={};for(const [name,args] of Object.entries(adapter.commands))commands[name]={program:adapter.program,args:[...args]};if(adapter.marker==='main.swift')commands.start={program:join(session.root,'.echo-build','Application'),args:[]};return {kind:adapter.kind,language:adapter.language,commands,missing:available?[]:[adapter.program],notes:['Detected adapter uses existing project manifests. Native GUI behavior, signing, platform SDKs and distributions need separate evidence. No toolchain is installed automatically.']};}
 if(files.includes('CMakeLists.txt'))return {kind:'configured',language:'C/C++',commands:{check:{program:'cmake',args:['-S','.','-B','.echo-build']},build:{program:'cmake',args:['--build','.echo-build']}},missing:[],notes:['Check configures CMake; build compiles configured targets. Choose an executable explicitly. Compiler/SDK availability is validated by actual exits.']};
 const java=files.filter(name=>name.endsWith('.java'));if(java.length)return {kind:'java',language:'Java',commands:{check:{program:'javac',args:['-d','.echo-build',...java]},build:{program:'javac',args:['-d','.echo-build',...java]}},missing:[],notes:['Top-level Java sources only. Package/classpath/dependency managers and main class must be configured explicitly for a real application.']};
 if(files.includes('index.html'))return {kind:'static-web',language:'HTML/CSS/JavaScript',commands:{check:{program:process.execPath,args:[join(getAppPath(),'scripts','coding_static_check.mjs')],nodeMode:true}},missing:[],notes:['No package install is needed for a static website. Use start_project_preview for a local preview.']};
 return {kind:'unknown',language:session.language??'undetected',commands:{},missing:[],notes:['Inspect the project and choose a verified adapter before promising a build. For a new simple website, create index.html, CSS and JavaScript with guarded patches.']};
}
export async function runProjectCheck(id:string,revision:number,name:string){const recipe=await detectRecipe(id);if(recipe.missing.length)throw new Error(`Missing toolchain: ${recipe.missing.join(', ')}`);const command=recipe.commands[name];if(name==='install'){const disk=await statfs(getSession(id).root);if(disk.bavail*disk.bsize<2*1024**3)throw new Error('Dependency installation needs at least 2 GiB free disk budget. Free space or choose a smaller recipe.');}if(!command)throw new Error(`No ${name} command is configured for ${recipe.kind}. Do not invent a passing check.`);if(command.args.some(arg=>arg.includes('.echo-build'))||command.program.includes('.echo-build'))await mkdir(await projectPath(getSession(id).root,'.echo-build'),{recursive:true});const fingerprint=await projectFingerprint(id);const previous=await (await import('./diagnostics.js')).inspectProjectDiagnostics(id);if(previous.stopRepair&&previous.checks.filter(c=>!c.stale&&c.name===name&&c.status==='failed').length>=3)throw new Error('Repeated unchanged failures reached the repair budget. Inspect diagnostics and resolve the blocker before retrying.');const launched=await startProcess(id,revision,{...command,timeoutMs:180000});await mutateSession(id,launched.revision,s=>{s.phase='verifying';s.artifacts.push({kind:'check',value:JSON.stringify({name,processId:launched.process.id,fingerprint:fingerprint.hash,contentRevision:s.contentRevision??0})});});return {...launched,revision:getSession(id).revision};}
