export const CODING_TOOL_NAMES = ['inspect_vercel_connection','assert_project_preview','inspect_project_recovery','start_project_application','prepare_vercel_deployment','deploy_vercel_preview','inspect_vercel_deployment','inspect_project_diagnostics','record_project_acceptance','finalize_project','interact_project_preview','start_project_preview','show_project_preview','inspect_project_preview','stop_project_preview','start_project_build','ask_build_question','answer_build_question','inspect_project_recipe','run_project_checks','open_project','inspect_project','search_project','read_project_file','apply_project_patch','update_project','start_process','read_process','write_process_input','stop_process','project_diff','undo_project_patch','project_git_status','create_project_worktree'];
export function codingToolNames(query:string):Set<string>{
  return /\b(?:build|code|coding|debug|compile|compiler|repository|repo|website|web\s?app|application|dev\s?server|project|terminal|typescript|javascript|python|rust|swift|npm|bug|patch|calculator|vercel)\b|projectId|processId|patchId|coding-project/i.test(query)?new Set(CODING_TOOL_NAMES):new Set();
}
export const CODING_GUIDANCE='For building or editing software, open_project first and retain its projectId/revision. Ask only blocking requirement questions; save acceptance criteria with update_project. Read/search files, patch against their current content hash, and inspect conflicts. Run builds/tests/dev servers with start_process; read_process reports actual logs and exit status. Stop only owned process IDs. Local previews and deployments require verification; file writes and process starts alone never prove the app works. Exercise preview controls, assert_project_preview on actual results, run_project_checks and record evidence for every acceptance criterion, then finalize_project. verify_task file_exists cannot replace project checks. For an intermediate file milestone only, verify_task scope artifact checks that artifact without claiming application completion. Installation is verified by the owned process exit, not by certifying the whole app. Automatically use run_supervised_task for substantial builds after resolving material requirements; no user mode switch is needed. Supply a concrete plan, observable acceptance criteria and existing project IDs. Assigned supervised workers implement and verify directly with project tools, without starting another coding worker. Keep small edits lightweight. Preserve user changes and use project_diff/undo_project_patch. If a coding action is absent from a small-context tool list, inspect_coding_tools returns its exact schema and invoke_coding_tool dispatches it through the same gate. A project directory is not an OS sandbox. Missing toolchains/services or quota are blockers, not success.';

/** Keep exact coding schemas and essential control flow; discover external services on demand. */
export const CODING_REQUEST_TOOLS=new Set([...CODING_TOOL_NAMES,'run_supervised_task','inspect_supervised_task','read_supervised_evidence','submit_task_review','cancel_supervised_task','show_task_report','read_browser_page','inspect_coding_tools','invoke_coding_tool','confirm_action','undo_last','remember','recall','forget','inspect_task','conversation_history','read_tool_result','update_task_plan','discover_tools','web_search']);
export function codingRequestToolAllowed(name:string):boolean{return CODING_REQUEST_TOOLS.has(name)||name.startsWith('mcp__');}
