import {readFile,readdir} from 'node:fs/promises';import {join,relative} from 'node:path';import {getSession,mutateSession} from './session.js';import {projectPath} from './workspace.js';import {projectFingerprint} from './snapshot.js';import {scrubSecrets} from '../safety/redact.js';
interface DeploymentPlan {fingerprint:string;projectId:string;vercelProject:string;teamId?:string;files:Array<{file:string;data:string;encoding:'base64'}>;}
async function request(path:string,method='GET',body?:unknown,transport=fetch){const token=process.env.VERCEL_TOKEN;if(!token)throw new Error('Vercel token is missing. Add it privately in API key settings; never speak or paste it into a build prompt.');const response=await transport(`https://api.vercel.com${path}`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const result=await response.json() as any;if(!response.ok)throw new Error(`Vercel ${response.status}: ${scrubSecrets(result.error?.message??'request failed')}`);return result;}
export async function prepareVercelDeployment(id:string,vercelProject:string,teamId?:string):Promise<DeploymentPlan>{const session=getSession(id);if(session.privateMode)throw new Error('Private builds require an explicit non-private publication decision.');if(!/^[a-zA-Z0-9_-]+$/.test(vercelProject)||teamId&&!/^[a-zA-Z0-9_-]+$/.test(teamId))throw new Error('Invalid Vercel project/team identifier.');const fingerprint=await projectFingerprint(id);const files:DeploymentPlan['files']=[];let bytes=0;
 async function visit(dir:string){for(const entry of await readdir(dir,{withFileTypes:true})){if(entry.name.startsWith('.')||['node_modules','dist','build','__pycache__'].includes(entry.name))continue;if(entry.isSymbolicLink())throw new Error('Deployment refuses symlinks.');const path=await projectPath(session.root,relative(session.root,join(dir,entry.name)));if(entry.isDirectory())await visit(path);else if(entry.isFile()){const data=await readFile(path);if(files.length+1>100||(bytes+=data.length)>1024*1024)throw new Error('Inline preview deployment is limited to 100 files / 1 MiB. Larger projects need the upload adapter.');if(/\.(?:env|pem|key|sqlite|db)$/i.test(entry.name)||/credentials|keys\.env/i.test(entry.name)||scrubSecrets(data.toString('utf8'))!==data.toString('utf8'))throw new Error('Deployment source contains possible credentials/private storage. Remove them before preparing publication.');files.push({file:relative(session.root,path).split('\\').join('/'),data:data.toString('base64'),encoding:'base64'});}}}
 await visit(session.root);if(!files.some(file=>file.file==='index.html'||file.file==='package.json'))throw new Error('No supported web entrypoint.');return {projectId:id,vercelProject,teamId,fingerprint:fingerprint.hash,files};}
const query=(teamId?:string)=>teamId?`?teamId=${encodeURIComponent(teamId)}`:'';
export async function inspectVercelConnection(teamId?:string,transport=fetch){
 if(teamId&&!/^[a-zA-Z0-9_-]+$/.test(teamId))throw new Error('Invalid Vercel team identifier.');
 const result=await request(`/v10/projects?limit=5${teamId?`&teamId=${encodeURIComponent(teamId)}`:''}`,'GET',undefined,transport);
 const projects=Array.isArray(result)?result:result.projects??[];
 return {connected:true,projects:projects.map((p:any)=>({id:p.id,name:p.name})),teamId,verification:'Authenticated read succeeded. Deployment permission and build success still need a real authorized preview deployment.'};
}
export async function deployVercelPreview(id:string,revision:number,project:string,teamId?:string,transport=fetch){if(!process.env.VERCEL_TOKEN)throw new Error('Vercel token is missing. Add it privately in API key settings.');const plan=await prepareVercelDeployment(id,project,teamId);const session=getSession(id);if(session.revision!==revision)throw new Error('Project revision conflict.');
 const previous=session.artifacts.filter(a=>a.kind==='vercel-deployment').map(a=>JSON.parse(a.value)).find(a=>a.fingerprint===plan.fingerprint&&a.project===project&&a.teamId===teamId);if(previous)return inspectVercelDeployment(id,previous.deploymentId,transport);
 if(session.artifacts.some(a=>a.kind==='vercel-submission'&&JSON.parse(a.value).fingerprint===plan.fingerprint))throw new Error('An earlier submission has an uncertain outcome. Inspect Vercel deployment history before resubmitting; duplicate publication is refused.');
 await mutateSession(id,revision,s=>{s.phase='deploying';s.artifacts.push({kind:'vercel-submission',value:JSON.stringify({fingerprint:plan.fingerprint,project,teamId,submittedAt:new Date().toISOString()})});});
 if((await projectFingerprint(id)).hash!==plan.fingerprint)throw new Error('Source changed during deployment preparation.');
 const result=await request(`/v13/deployments${query(teamId)}`,'POST',{name:project,project,files:plan.files,meta:{echoProject:id,echoFingerprint:plan.fingerprint}},transport);if(typeof result.id!=='string')throw new Error('Vercel did not return a deployment ID; inspect remote history before retrying.');const current=getSession(id);await mutateSession(id,current.revision,s=>{s.artifacts.push({kind:'vercel-deployment',value:JSON.stringify({deploymentId:result.id,fingerprint:plan.fingerprint,project,teamId})});});return {deploymentId:result.id,state:result.readyState??result.status,verification:'submitted; poll inspect_vercel_deployment until READY and verify preview'};
}
export async function inspectVercelDeployment(id:string,deploymentId:string,transport=fetch){const session=getSession(id);const artifact=session.artifacts.filter(a=>a.kind==='vercel-deployment').map(a=>JSON.parse(a.value)).find(a=>a.deploymentId===deploymentId);if(!artifact)throw new Error('Deployment is not owned by this project.');const result=await request(`/v13/deployments/${encodeURIComponent(deploymentId)}${query(artifact.teamId)}`,'GET',undefined,transport);const state=result.readyState??result.status;let url:string|undefined;if(result.url){const parsed=new URL(`https://${result.url}`);if(!parsed.hostname.endsWith('.vercel.app')||parsed.username||parsed.password||parsed.port)throw new Error('Unexpected deployment URL.');url=parsed.href;}return {deploymentId,state,url,sourceStale:(await projectFingerprint(id)).hash!==artifact.fingerprint,verification:state==='READY'?'Provider reports ready; protected preview and user flows still require independent verification.':'not ready'};}
